### ISSUE TITLE
一个改进的建议。

### ISSUE THREAD

**Issue by perfectsun1990** [zymill/flvAnalyser#1]
1、首先，对作者表示感谢，该工具相对其他开源的工具界面友好一点。
2、其次，如果作者不希望该工具没落，可以开源出来，这样对工具和你的影响力有帮助。
3、tag界面弹出显示不太好，另外建议添加字段高亮hex的逻辑，以及实时播放/帧进关联功能。

**Comment by zymill** [comment]
Sunpf: 抱歉，回复晚了。衷心感谢您的宝贵建议。最近计划利用10.1假期更新一个的新版本，待准备好后，将发布给大家试用。届时还望多多指正。

**Comment by zymill** [comment]
已经更新了版本，欢迎下载试用。

**Comment by perfectsun1990** [comment]
好的，已经在用，感觉好用很多，再次感谢。

sunpf
