### ISSUE TITLE
Window10 下面菜单项 显示乱码

### ISSUE THREAD

**Issue by junco-tian** [zymill/flvAnalyser#10]
windows 10下 ，在 codepage 设置为 65001 时 显示乱码，建议可以增加英文菜单显示

**Comment by zymill** [comment]
windows 10下 ，在 codepage 设置为 65001 时 显示乱码？这个具体指什么，没弄明白。

**Comment by zymill** [comment]
能提供个抓图或其他信息参考下不？（hybase@qq.com）

**Comment by FredZeng** [comment]
![image](https://user-images.githubusercontent.com/17154608/220573522-1a89428d-1fdf-4bbd-a741-d963762c7418.png)
![image](https://user-images.githubusercontent.com/17154608/220573581-515b75ed-2405-4248-beba-7e2fcbf2a75e.png)
同样遇到乱码问题，操作系统如下：
![image](https://user-images.githubusercontent.com/17154608/220573780-6051afe9-3221-4eb6-917c-07b7ec8036d2.png)


PS: 能不能支持调整字体大小，字太小了看起来难受

**Comment by zymill** [comment]
真心感谢您反馈的问题！

从您抓图看，不仅乱码和菜单栏空白，而且工具栏中的文字显示也不全。因为没有和您相同的系统环境。暂时无法排查原因。flvAnalyser开发用的是windows系统中文默认字体，没采用其他特殊的字体。当前出现的问题可能和系统有密切关系（您在用的系统是否有区分utf-8和gbk？）。

正常显示的如下图
![20230226140226](https://user-images.githubusercontent.com/18504455/221395011-2e21152f-758b-49f1-8f48-ff43856fe187.png)

如果有条件，请试下其他不同版本的window-10系统！
thanks!

**Comment by zymill** [comment]
调整字体大小功能，暂没想好如何实现。字体大小变化会影响整体布局，可能带来其他新问题，等研究后再确认下。

平常您暂可以先通过windows放大功能应对下。

**Comment by FredZeng** [comment]
@zymill 的确是因为我将系统的默认字符集改为了 utf8，可以考虑兼容一下这种情况
![image](https://user-images.githubusercontent.com/17154608/223306553-b5acc2e2-e488-4224-9862-5b55909594ef.png)

PS：工具很赞，issue 响应也很迅速

**Comment by zymill** [comment]
尽量兼容

**Comment by zymill** [comment]
utf8环境下，可以试下 v0.1.2.000 英文界面，看看是否能正常使用？

**Comment by zymill** [comment]
欢迎反馈英文版(v0.1.2.000)遇到的问题。

**Comment by FredZeng** [comment]
> 欢迎反馈英文版(v0.1.2.000)遇到的问题。

似乎从某个版本开始就支持显示 nalu 信息了，这个功能很赞；建议不妨在 readme 中贴个微信/支付宝收款码，工具真的很好用；
更期待以后能支持 mac 版本~

**Comment by zymill** [comment]
已经发布英文版本，遇到乱码的情况，建议使用英文版本。
close issue。
