### ISSUE TITLE
请问实时流分析能否支持更长的url呢

### ISSUE THREAD

**Issue by DSniperCHEN** [zymill/flvAnalyser#12]
最新版本(v0.1.1.000)支持了实时流，但url长度貌似被输入框限制了长度（貌似是不到100个字符），可以支持更长的url么

**Comment by zymill** [comment]
没有意料到这个问题，截图给我看下?

**Comment by zymill** [comment]
不用截图了，我已经试过。

**Comment by zymill** [comment]
已经更新，请下载晚上更新的版本验证。
