### ISSUE TITLE
由于找不到 MSVCR120.dll，无法继续执行代码。重新安装程序可能会解决此问题。 

### ISSUE THREAD

**Issue by xengine-qyt** [zymill/flvAnalyser#13]
怎么意思 0.1.2版本

刚下的.运行就报错,下了几个MSVCR120发现用不了,已启动就报错

**Comment by zymill** [comment]
https://zhuanlan.zhihu.com/p/623106722
请参考上面链接最后的说明（看看是否能解决）

**Comment by xengine-qyt** [comment]
建议一起提供或者升级到VS2015以后得版本

**Comment by zymill** [comment]
> 建议一起提供或者升级到VS2015以后得版本

thx！后期完善。
