### ISSUE TITLE
大佬什么时候辛苦支持下h266^-^

### ISSUE THREAD

**Issue by feiwei9696** [zymill/flvAnalyser#15]

**Comment by zymill** [comment]
flv 用 h266 现在应该还没有产品吧？

**Comment by MaoJianwei** [comment]
这个软件不仅可以解码flv，还可以直接解码h264裸数据流（视频轨），很赞！估计这位兄弟是想要可以解码h264裸数据流。

**Comment by zymill** [comment]
解析H.266 ES数据功能，需要腾个充裕的时间来准备。后期争取加上。

**Comment by zymill** [comment]
能提供一些 vvc es data 素材么？@feiwei9696

**Comment by zymill** [comment]
vps/sps/pps/sei中数据字段能覆盖 dpd/general hrd/ols hrd/vui等结构，最佳。

**Comment by zymill** [comment]
联系方式
email: hybase@qq.com
或
微信   hybase

**Comment by zymill** [comment]
since v0.2.0.001, flvAnalyser can support H266/VVC ES analysis!
Welcome to try it!
