### ISSUE TITLE
perf: 考虑兼容 MSVCR120.dll 不存在的场景

### ISSUE THREAD

**Issue by FredZeng** [zymill/flvAnalyser#17]
软件似乎是使用到了一些比较旧的系统API？在一些电脑上运行，会报以下错误：
![image](https://github.com/zymill/flvAnalyser/assets/17154608/c43c8d27-8697-43b0-930a-caaaae2ebf17)

当然，有经验的人可以去微软官网上安装对应环境 [vcredist_x86.exe](https://www.microsoft.com/zh-cn/download/details.aspx?id=40784)，在这里记录一下；
建议看是否能直接内置这个 dll，尽量做到开箱即用；
PS：再次感谢作者开发了这么好用的工具~

**Comment by FredZeng** [comment]
看起来和 https://github.com/zymill/flvAnalyser/issues/13 重复了，建议在 README 中补充一下这种情况处理吧，可能算是一个普遍出现的小问题

**Comment by zymill** [comment]
Thanks!
已经在README补充，后期考虑将dll携带压缩一起发布
