### ISSUE TITLE
Enhanced FLV问题反馈

### ISSUE THREAD

**Issue by flying1314** [zymill/flvAnalyser#18]
1、使用h265视频格式时，提取视频时卡死，强制关掉程序后保存的h265文件内容也是不对的
2、有B帧时界面显示所有帧都是B帧，其实是有P帧的，显示不正确
3、h265和av1都无法单击某个NALU或OBU定位到二进制位置高亮，如VPS、SPS这些
4、av1是没有composition time的，但UI显示了

**Comment by zymill** [comment]
方便提供用的flv文件吗？微信（hybase）或email: hybase@qq.com

**Comment by flying1314** [comment]
文件没有什么特殊性，就常规的enhanced flv就会发现这些问题，你也可以从ffmpeg官网下载已经编译好的git最新代码的可执行程序生成enhanced flv就可以发现上面几个问题

**Comment by zymill** [comment]
请方便时提供下测试用的文件。我这里暂没法复现问题。不确定是否和hevc数据有关。

**Comment by flying1314** [comment]
不是某个特殊文件，我这边随便一个265都会有这些问题，你也可以用obs使用QSV编码生成265推流到srs，拉265复现，按道理你那边随便编码一个265用enhanced格式都能复现，还有enhanced av1那几个问题也是必现

**Comment by zymill** [comment]
朋友，请方便时提供你测试中已经遇到问题的素材。提供一下测试中的log信息。

**Comment by zymill** [comment]
2、有B帧时界面显示所有帧都是B帧，其实是有P帧的，显示不正确

特别是这个问题的素材

**Comment by flying1314** [comment]
> 2、有B帧时界面显示所有帧都是B帧，其实是有P帧的，显示不正确
> 
> 特别是这个问题的素材

这个就是用obs编码的enhanced 265推流的，你下载obs推流试下，没什么特殊的

**Comment by zymill** [comment]
朋友，请方便时直接提供你测试中已经遇到问题的素材。并提供一下测试中的log信息。
如果涉及公司版权或其他原因，不能提供，请明确说明下。

我这里暂时无法复现问题。

**Comment by zglloo** [comment]
我是用的是 OBS 30.0.0-rc2 推流到我自己的源站录制的flv 和 .h265 没发现什么异常
https://wwxf.lanzouw.com/i7PKj1dm189a   [文件下载地址]


`CompleteName                    : OBS push hevc.flv
Format/String                   : Flash Video
FileSize/String                 : 12.1 MiB
Duration/String                 : 1mn 28s
OverallBitRate/String           : 1148 Kbps
Encoded_Application/String      : obs-output module (libobs version 30.0.0-rc2)
2.1                             : No
3.1                             : No
4.0                             : No
4.1                             : No
5.1                             : No
7.1                             : No

Video

Format/String                   : HEVC
Format/Info                     : High Efficiency Video Coding
Format_Profile                  : Main@L4@Main
CodecID                         : 12
Duration/String                 : 1mn 28s
BitRate/String                  : 2500 Kbps
Width/String                    : 1920 pixel
Height/String                   : 1080 pixel
DisplayAspectRatio/String       : 16:9
FrameRate_Mode/String           : CFR
FrameRate/String                : 25.000 fps
ColorSpace                      : YUV
ChromaSubsampling/String        : 4:2:0
BitDepth/String                 : 8 bit
Bits-(Pixel*Frame)              : 0.048
StreamSize/String               : 26.3 MiB
colour_range                    : Limited
colour_primaries                : BT.709
transfer_characteristics        : BT.709
matrix_coefficients             : BT.709`

**Comment by flying1314** [comment]
你这个文件都不是Enhanced FLV格式啊，而且没有B帧，用OBS推设置下bframes=3，你拉的FLV要用Enhanced FLV格式，就是跟Enhanced RTMP一样的，通过foucCC设置的，不是id=12的方式，你用ffmpeg官网的转下就是Enhanced FLV格式了

**Comment by zymill** [comment]
早期架构的英伟达和英特尔卡都可能不支持B帧。
测试环境不尽相同。

**Comment by zymill** [comment]
** update to v0.1.2.006
1. bug-fix: fix extrack hevc es from enhanced flv 
2. bug-fix: fix av1 without composition time**

## 有待后续处理
2、有B帧时界面显示所有帧都是B帧，其实是有P帧的，显示不正确
答复：手边全部hevc相关素材都试过，暂没复现

3、h265和av1都无法单击某个NALU或OBU定位到二进制位置高亮，如VPS、SPS这些
答复：功能可能不完善。请帮忙提供抓图标注些具体的说明。
