### ISSUE TITLE
feature: 筛选过后显示帧索引（序号）

### ISSUE THREAD

**Issue by FredZeng** [zymill/flvAnalyser#20]
图片无法上传，请见谅~

工具本身支持筛选 FLV video tag 和 FLV audio tag，但是筛选过后详情列表的“序号”一列显示的是 tag 在整个 flv 文件中的序号（即属于第几个tag）；
这时候会有一个痛点，假如我要计算一下两个 I 帧之间实际有多少帧，我就得一帧一帧去数；
能否再增加一列用来显示 tag 在当前筛选后的列表中的索引呢？

**Comment by zymill** [comment]
The audio/video tag index will be added in next version, as below.

index
1 (2)
2 (4)
3 (7)
