### ISSUE TITLE
【功能建议】能否作为rtmp server接收推流

### ISSUE THREAD

**Issue by zaccheodong** [zymill/flvAnalyser#21]
这是目前使用下来最便捷的一个flv/rtmp 码流的分析工具了。感谢！

# 功能建议
有时需要对rtmp 推流端的码流进行分析，是否可以支持此模式？具体如下
1. 在“文件” 菜单中增加“监听并接收推流”。此处还需要配置一个本地监听的端口如1935
2. 通过ffmpeg 或其它推流工具 使用rtmp协议推流到 步骤1配置的端口
3. 使用flvAnalyser现有的UI交互，对码流进行分析

**Comment by zymill** [comment]
首先非常感谢你提出的建议！

所提到的功能，大概有一种方式可以协助分析，先用 srs 或 nginx-http-flv-module做 RTMP收流端。然后flvAnalyser 播放 srs 或 nginx-http-flv-module中转的RTMP。

如果上传流本身有问题，flvAnalyser分析工具分析RTMP推流，和 srs或nginx-http-flv-module提供的日志都能定位问题。

鉴于此，暂没计划在flvAnalyser中实现类 nginx-http-flv-module的功能。

希望这个方法对你有用。谢谢！
