### ISSUE TITLE
历史版本是否可以删除，避免下载master太大下载超久

### ISSUE THREAD

**Issue by flying1314** [zymill/flvAnalyser#22]
由于某些网络原因无法单独点击某个版本进行下载，需要整个master下载，时间太久了，建议删除历史版本，或者放在release那边，需要的人自己去下载，正常都会下载最新的

**Comment by zymill** [comment]
好滴！

**Comment by zymill** [comment]
大部分历史版本已经从master移除了。

**Comment by flying1314** [comment]
> 大部分历史版本已经从master移除了。

还是太大了，好几百M了，release那边的版本是否可以不包含历史版本呢？跟其他软件的发布一样，每次只发布当前版本，需要历史版本自己去下载历史的release
