### ISSUE TITLE
运行程序无任何反应？

### ISSUE THREAD

**Issue by LeoYanlv** [zymill/flvAnalyser#25]
运行flvAnalyser.exe，v0.2.0.003，win11，没报错也没UI显示，不知道什么情况？

**Comment by zglloo** [comment]
你的win11版本是什么，能否提供目录中\flvAnalyser v0.2.0.003\log  压缩打包下上传看下

**Comment by LeoYanlv** [comment]
[log.zip](https://github.com/user-attachments/files/16902586/log.zip)
版本	Windows 11 专业版
版本号	23H2
安装日期	‎2023-‎1-‎19
操作系统版本	22631.4112
体验	Windows Feature Experience Pack 1000.22700.1034.0

**Comment by zglloo** [comment]
能否下载历史版本试试是否也有类似情况，内容中百度网盘下载
https://zhuanlan.zhihu.com/p/623106722

**Comment by zymill** [comment]
Please supply more log with  log level debug. Thx!
@LeoYanlv

**Comment by zglloo** [comment]
版本	Windows 11 家庭中文版
版本号	23H2
安装日期	‎2023/‎1/‎30
操作系统版本	22631.4169
体验	Windows Feature Experience Pack 1000.22700.1034.0
Windows 11 Version 23H2 的 09 累积更新，适合基于 x64 的系统 (KB5043076)
我这里更新本月的补丁正常没有任何问题运行v0.2.0.004

**Comment by LeoYanlv** [comment]
我家里和公司都是一样的配置，一样的系统版本
开始都不能运行，家里电脑今天一试又可以了，
公司电脑还是不行，在什么都没有变动的情况下，我把公司电脑重启了一下，就可以了
[server.log](https://github.com/user-attachments/files/17038158/server.log)
从第7行开始是重启后的日志

**Comment by zymill** [comment]
> 我家里和公司都是一样的配置，一样的系统版本 开始都不能运行，家里电脑今天一试又可以了， 公司电脑还是不行，在什么都没有变动的情况下，我把公司电脑重启了一下，就可以了 [server.log](https://github.com/user-attachments/files/17038158/server.log) 从第7行开始是重启后的日志

日志中看不出原因。issue暂时关闭了。
