### ISSUE TITLE
请问考虑过实时流分析吗？

### ISSUE THREAD

**Issue by cgoder** [zymill/flvAnalyser#3]
类似ts分析仪这样的。方便对实时流式文件进行分析。

input模拟抽象出来，interface化，可以read/parse类似 file/stream等不同类型的数据

**Comment by zymill** [comment]
暂时还没考虑。可以先通过录流分析

**Comment by zymill** [comment]
新版本v0.1.1.001已经支持RTMP/HTTP-FLV网络接入，请知悉！
