### ISSUE TITLE
可以加上av1和opus的解析吗？

### ISSUE THREAD

**Issue by flyboyxiang** [zymill/flvAnalyser#4]
目前很多cdn都支持av1了，opus也开始由于rtc的兴起逐步支持了，av1的id是13，opus的id也是13，一个是视频，一个是音频，网上开源的https://github.com/ireader/media-server
里面也有flv-av1和flv-opus的实现，希望作者可以加上这两个，这个工具确实好用

**Comment by zymill** [comment]
多谢提供建议，可以后续支持上，有样例文件？如果有请发送一份给我: hybase@qq.com。

**Comment by flyboyxiang** [comment]
我本地暂时没有，你可以先用上面那个项目的libflv生成测试文件，后面我本地可以生成了也提供下

**Comment by zymill** [comment]
好，因为我手上有急事要处理，而且周期有点长。短期内还没空加av1+opus格式。有样例文件后可以随时发给我，方便后面可以多测试。

**Comment by flyboyxiang** [comment]
好的

**Comment by zymill** [comment]
版本v.0.0.3.002 添加了AV1，请知悉！
