### ISSUE TITLE
对.H264文件（ES流）的nal_raf_idc字段解析有误，始终是0。

### ISSUE THREAD

**Issue by MaoJianwei** [zymill/flvAnalyser#7]
在左侧字节窗口中看到是0x65、0x41，但右侧的字段解析窗口中，nal_ref_idc字段始终是0。
![无标题111](https://user-images.githubusercontent.com/12800168/187151705-4139b41b-205e-4d9b-91ce-90b682e8152d.png)

**Comment by MaoJianwei** [comment]
这个工具太方便了！超出预期！顺便点个赞！

**Comment by zymill** [comment]
Thanks for your issue! The problem has been fixed in v0.0.5.002.

**Comment by MaoJianwei** [comment]
Thank you very much!
