### ISSUE TITLE
在打开.FLV文件时，如果能对每个视频帧的NALU header的字段也详细解析，就更好了！

### ISSUE THREAD

**Issue by MaoJianwei** [zymill/flvAnalyser#8]
现在只能解析FLV tag的字段，NALU header的字段没解析出来，比如比较重要的nal_ref_idc、nal_unit_type字段
![无标题111](https://user-images.githubusercontent.com/12800168/187152504-dcdb8b5d-d3c2-485f-947c-5a522f1357db.png)

**Comment by zymill** [comment]
show nal unit header info since v0.2.0.003.
Pls try it!
