### ISSUE TITLE
win10打开最新的flvAnalyser v0.0.5.002.7z直接被报毒、删除了，望帮忙看下；

### ISSUE THREAD

**Issue by sunpengfei0307** [zymill/flvAnalyser#9]
这个版本 还没有问题，flvAnalyser v0.0.4.004；+

**Comment by zymill** [comment]
只是增加了曲线缩放，历史文件列表功能。可能是被误判了吧。我自己这里的win10上没有这样的提示。

2022.08.31 14:25:25                                           v0.0.5.002
----------------------------------------------------------------------------------
1. add-opt:增加AMF标识;
2. bug-fix:修复已知问题;

2022.08.07 22:55:25                                           v0.0.5.001
----------------------------------------------------------------------------------
1. add-opt:支持tag类型筛选;
2. add-opt:支持历史文件列表;
3. add-opt:支持时间戳的缩放观察;

**Comment by duiniuluantanqin** [comment]
能否开放源码学习一下呀？

**Comment by zymill** [comment]
原被杀毒工具报毒问题，最近更新了版本，可以试试问题是否存在？
原来检查新版本用了超链接。现在去除了。
![66fc4c37671ddf17e667c706f88d358](https://user-images.githubusercontent.com/18504455/233073771-8e8e0b2c-0edc-4440-9aa5-5e8d860b3118.png)

**Comment by sunpengfei0307** [comment]
好的，我再试试~  如果还有问题我这里回复你~在 2023年4月19日，20:24，zymill ***@***.***> 写道：﻿
原被杀毒工具报毒问题，最近更新了版本，可以试试问题是否存在？
原来检查新版本用了超链接。现在去除了。
